import {
  addDoc,
  collection,
  onSnapshot,
  doc,
  updateDoc,
  query,
  where,
  setDoc,
  deleteDoc,
  orderBy,
  serverTimestamp,
  getDocs,
  getFirestore,
} from "firebase/firestore";
import { toast } from "react-toastify";
import { app, firestore } from "../../firebase/config";
import { SignUpDto } from "../../@types/dto/SignUpDto";
import { User } from "../../@types/entities/User";

const userRef = collection(firestore, "users");

export const postUserData = async (object: Partial<User>) => {
  addDoc(userRef, object)
    .then(() => {})
    .catch((err) => {
      console.log(err);
    });
};

// TODO: change type
export const addUserPost = async (post: any) => {
  const docRef = await addDoc(collection(firestore, "publications"), post);

  // Get the reference number (ID) generated by Firestore for the new document
  const referenceNumber = docRef.id;

  // Update the post object with the reference number
  const postWithReferenceNumber = { ...post, id: referenceNumber };

  // Update the document with the post object containing the reference number
  await updateDoc(
    doc(firestore, "publications", referenceNumber),
    postWithReferenceNumber
  );

  return postWithReferenceNumber;
};

// export const users = async () => {
//   const querySnapshot = await getDocs(userRef);

//   querySnapshot.forEach((doc) => {
//     console.log("Document data:", doc.data());
//   });
// };
